[package]
name = "markov"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33"
rand = { version = "~0.8", features = [ "small_rng" ] }
titlecase = "1.0"
regex = "1.4"
rand_chacha = "0.3"

[dev-dependencies]
tempfile = "3.2"
